create table if not exists public.speech_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  character_count integer not null check (character_count between 1 and 300),
  requested_at timestamptz not null default now()
);

create index if not exists speech_usage_user_requested_idx
  on public.speech_usage (user_id, requested_at desc);

alter table public.speech_usage enable row level security;

create or replace function public.consume_speech_quota(p_character_count integer)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_recent_requests integer;
  v_daily_characters integer;
begin
  if v_user_id is null or p_character_count not between 1 and 300 then
    return false;
  end if;

  perform 1 from public.profiles where id = v_user_id for update;

  delete from public.speech_usage
  where user_id = v_user_id
    and requested_at < now() - interval '7 days';

  select count(*) into v_recent_requests
  from public.speech_usage
  where user_id = v_user_id
    and requested_at >= now() - interval '5 minutes';

  select coalesce(sum(character_count), 0) into v_daily_characters
  from public.speech_usage
  where user_id = v_user_id
    and requested_at >= now() - interval '24 hours';

  if v_recent_requests >= 12 or v_daily_characters + p_character_count > 1500 then
    return false;
  end if;

  insert into public.speech_usage (user_id, character_count)
  values (v_user_id, p_character_count);

  return true;
end;
$$;

revoke all on function public.consume_speech_quota(integer) from public;
grant execute on function public.consume_speech_quota(integer) to authenticated;

drop policy if exists "Users can create their own assessment attempts" on public.assessment_attempts;
drop policy if exists "Users can update their own assessment attempts" on public.assessment_attempts;
drop policy if exists "Users can create their own assessment answers" on public.assessment_answers;

create or replace function public.complete_level_assessment(
  p_answers integer[],
  p_accepted_level text
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_correct integer[] := array[1, 1, 1, 2, 1, 0, 1, 0];
  v_keys text[] := array[
    'plans_subjunctive',
    'past_narrative',
    'purpose_para',
    'conditional',
    'reported_request',
    'connector',
    'past_hypothesis',
    'nuanced_expression'
  ];
  v_score integer := 0;
  v_recommended_level text;
  v_attempt_id uuid;
  v_index integer;
begin
  if v_user_id is null or array_length(p_answers, 1) is distinct from 8 then
    raise exception 'Invalid assessment submission';
  end if;

  for v_index in 1..8 loop
    if p_answers[v_index] not between 0 and 2 then
      raise exception 'Invalid assessment answer';
    end if;
    if p_answers[v_index] = v_correct[v_index] then
      v_score := v_score + 1;
    end if;
  end loop;

  v_recommended_level := case
    when v_score <= 2 then 'A2'
    when v_score <= 5 then 'B1'
    when v_score <= 7 then 'B2'
    else 'C1'
  end;

  if p_accepted_level is distinct from v_recommended_level then
    raise exception 'Assessment level does not match score';
  end if;

  insert into public.assessment_attempts (
    user_id, status, score, total_points, recommended_level,
    accepted_level, completed_at
  ) values (
    v_user_id, 'completed', v_score, 8, v_recommended_level,
    p_accepted_level, now()
  ) returning id into v_attempt_id;

  for v_index in 1..8 loop
    insert into public.assessment_answers (
      attempt_id, user_id, question_key, selected_answer, is_correct, points
    ) values (
      v_attempt_id,
      v_user_id,
      v_keys[v_index],
      p_answers[v_index]::text,
      p_answers[v_index] = v_correct[v_index],
      case when p_answers[v_index] = v_correct[v_index] then 1 else 0 end
    );
  end loop;

  return v_attempt_id;
end;
$$;

revoke all on function public.complete_level_assessment(integer[], text) from public;
grant execute on function public.complete_level_assessment(integer[], text) to authenticated;

drop policy if exists "Users can create their own lesson attempts" on public.lesson_attempts;
drop policy if exists "Users can update their own lesson attempts" on public.lesson_attempts;
drop policy if exists "Users can create their own lesson responses" on public.lesson_responses;
drop policy if exists "Users can update their own lesson responses" on public.lesson_responses;

create or replace function public.start_lesson_attempt(p_lesson_id uuid)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_total integer;
  v_attempt_id uuid;
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;

  select count(*) into v_total
  from public.lesson_activities
  join public.lessons on lessons.id = lesson_activities.lesson_id
  where lesson_activities.lesson_id = p_lesson_id
    and lessons.is_published;

  if v_total < 1 then
    raise exception 'Lesson is unavailable';
  end if;

  insert into public.lesson_attempts (user_id, lesson_id, total_activities)
  values (v_user_id, p_lesson_id, v_total)
  returning id into v_attempt_id;

  return v_attempt_id;
end;
$$;

revoke all on function public.start_lesson_attempt(uuid) from public;
grant execute on function public.start_lesson_attempt(uuid) to authenticated;

create or replace function public.submit_lesson_response(
  p_attempt_id uuid,
  p_activity_id uuid,
  p_answer text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_correct_answer text;
  v_is_correct boolean;
begin
  if v_user_id is null or p_answer is null then
    raise exception 'Invalid lesson response';
  end if;

  select lesson_activities.correct_answer into v_correct_answer
  from public.lesson_attempts
  join public.lesson_activities
    on lesson_activities.lesson_id = lesson_attempts.lesson_id
  where lesson_attempts.id = p_attempt_id
    and lesson_attempts.user_id = v_user_id
    and lesson_attempts.status = 'in_progress'
    and lesson_activities.id = p_activity_id;

  if v_correct_answer is null then
    raise exception 'Invalid lesson activity';
  end if;

  v_is_correct := p_answer = v_correct_answer;

  insert into public.lesson_responses (
    attempt_id, activity_id, user_id, answer, is_correct
  ) values (
    p_attempt_id, p_activity_id, v_user_id, p_answer, v_is_correct
  )
  on conflict (attempt_id, activity_id) do update
    set answer = excluded.answer,
        is_correct = excluded.is_correct,
        answered_at = now()
    where lesson_responses.user_id = v_user_id;

  return v_is_correct;
end;
$$;

revoke all on function public.submit_lesson_response(uuid, uuid, text) from public;
grant execute on function public.submit_lesson_response(uuid, uuid, text) to authenticated;

create or replace function public.complete_lesson_attempt(p_attempt_id uuid)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_score integer;
  v_total integer;
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;

  select total_activities into v_total
  from public.lesson_attempts
  where id = p_attempt_id
    and user_id = v_user_id
    and status = 'in_progress'
  for update;

  if v_total is null then
    raise exception 'Invalid lesson attempt';
  end if;

  select count(*) filter (where is_correct) into v_score
  from public.lesson_responses
  where attempt_id = p_attempt_id
    and user_id = v_user_id;

  update public.lesson_attempts
  set status = 'completed', score = v_score, completed_at = now()
  where id = p_attempt_id and user_id = v_user_id;

  return v_score;
end;
$$;

revoke all on function public.complete_lesson_attempt(uuid) from public;
grant execute on function public.complete_lesson_attempt(uuid) to authenticated;
