create table public.assessment_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  status text not null default 'in_progress',
  score integer,
  total_points integer,
  recommended_level text,
  accepted_level text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint assessment_attempts_status
    check (status in ('in_progress', 'completed', 'abandoned')),
  constraint assessment_attempts_score
    check (score is null or score >= 0),
  constraint assessment_attempts_total_points
    check (total_points is null or total_points > 0),
  constraint assessment_attempts_score_within_total
    check (score is null or total_points is null or score <= total_points),
  constraint assessment_attempts_completed_fields
    check (
      status <> 'completed'
      or (score is not null and total_points is not null and recommended_level is not null and completed_at is not null)
    ),
  constraint assessment_attempts_recommended_level
    check (recommended_level is null or recommended_level in ('A1', 'A2', 'B1', 'B2', 'C1', 'C2')),
  constraint assessment_attempts_accepted_level
    check (accepted_level is null or accepted_level in ('A1', 'A2', 'B1', 'B2', 'C1', 'C2'))
);

create index assessment_attempts_user_created_idx
  on public.assessment_attempts (user_id, created_at desc);

create table public.assessment_answers (
  id bigint generated by default as identity primary key,
  attempt_id uuid not null references public.assessment_attempts (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  question_key text not null,
  selected_answer text not null,
  is_correct boolean not null,
  points integer not null default 0,
  created_at timestamptz not null default now(),

  constraint assessment_answers_question_key_length
    check (char_length(question_key) between 1 and 100),
  constraint assessment_answers_points
    check (points >= 0),
  constraint assessment_answers_attempt_question_unique
    unique (attempt_id, question_key)
);

create index assessment_answers_user_attempt_idx
  on public.assessment_answers (user_id, attempt_id);

alter table public.assessment_attempts enable row level security;
alter table public.assessment_answers enable row level security;

create policy "Users can read their own assessment attempts"
  on public.assessment_attempts for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can create their own assessment attempts"
  on public.assessment_attempts for insert to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their own assessment attempts"
  on public.assessment_attempts for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can read their own assessment answers"
  on public.assessment_answers for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can create their own assessment answers"
  on public.assessment_answers for insert to authenticated
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.assessment_attempts
      where assessment_attempts.id = assessment_answers.attempt_id
        and assessment_attempts.user_id = (select auth.uid())
    )
  );

create function public.set_assessment_attempt_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger assessment_attempts_set_updated_at
  before update on public.assessment_attempts
  for each row
  execute function public.set_assessment_attempt_updated_at();
