create table public.lessons (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null,
  level text not null,
  estimated_minutes integer not null default 5,
  is_published boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint lessons_level check (level in ('A1', 'A2', 'B1', 'B2', 'C1', 'C2')),
  constraint lessons_estimated_minutes check (estimated_minutes between 1 and 60),
  constraint lessons_published_at check (not is_published or published_at is not null)
);

create table public.lesson_activities (
  id uuid primary key default gen_random_uuid(),
  lesson_id uuid not null references public.lessons (id) on delete cascade,
  position integer not null,
  activity_type text not null,
  instruction text not null,
  prompt text not null,
  options jsonb not null,
  correct_answer text not null,
  explanation text not null,
  audio_text text,
  created_at timestamptz not null default now(),

  constraint lesson_activities_position check (position > 0),
  constraint lesson_activities_type check (activity_type in ('vocabulary', 'listening', 'grammar', 'response')),
  constraint lesson_activities_options_array check (jsonb_typeof(options) = 'array'),
  constraint lesson_activities_lesson_position_unique unique (lesson_id, position)
);

create table public.lesson_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  lesson_id uuid not null references public.lessons (id) on delete cascade,
  status text not null default 'in_progress',
  score integer not null default 0,
  total_activities integer not null,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now(),

  constraint lesson_attempts_status check (status in ('in_progress', 'completed', 'abandoned')),
  constraint lesson_attempts_score check (score >= 0 and score <= total_activities),
  constraint lesson_attempts_total check (total_activities > 0),
  constraint lesson_attempts_completion check (status <> 'completed' or completed_at is not null)
);

create index lesson_attempts_user_completed_idx
  on public.lesson_attempts (user_id, completed_at desc)
  where status = 'completed';

create table public.lesson_responses (
  id bigint generated by default as identity primary key,
  attempt_id uuid not null references public.lesson_attempts (id) on delete cascade,
  activity_id uuid not null references public.lesson_activities (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  answer text not null,
  is_correct boolean not null,
  answered_at timestamptz not null default now(),

  constraint lesson_responses_attempt_activity_unique unique (attempt_id, activity_id)
);

alter table public.lessons enable row level security;
alter table public.lesson_activities enable row level security;
alter table public.lesson_attempts enable row level security;
alter table public.lesson_responses enable row level security;

create policy "Authenticated users can read published lessons"
  on public.lessons for select to authenticated
  using (is_published);

create policy "Authenticated users can read published lesson activities"
  on public.lesson_activities for select to authenticated
  using (exists (
    select 1 from public.lessons
    where lessons.id = lesson_activities.lesson_id
      and lessons.is_published
  ));

create policy "Users can read their own lesson attempts"
  on public.lesson_attempts for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can create their own lesson attempts"
  on public.lesson_attempts for insert to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their own lesson attempts"
  on public.lesson_attempts for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can read their own lesson responses"
  on public.lesson_responses for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can create their own lesson responses"
  on public.lesson_responses for insert to authenticated
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.lesson_attempts
      where lesson_attempts.id = lesson_responses.attempt_id
        and lesson_attempts.user_id = (select auth.uid())
    )
  );

create policy "Users can update their own lesson responses"
  on public.lesson_responses for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create function public.set_lesson_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger lessons_set_updated_at
  before update on public.lessons
  for each row execute function public.set_lesson_updated_at();

create trigger lesson_attempts_set_updated_at
  before update on public.lesson_attempts
  for each row execute function public.set_lesson_updated_at();

insert into public.lessons (id, title, description, level, estimated_minutes, is_published, published_at)
values (
  'b2000000-0000-4000-8000-000000000001',
  'Making plans naturally',
  'Practice talking about plans, conditions, and possibilities in everyday Spanish.',
  'B2',
  5,
  true,
  now()
);

insert into public.lesson_activities (id, lesson_id, position, activity_type, instruction, prompt, options, correct_answer, explanation, audio_text)
values
  (
    'b2000000-0000-4000-8000-000000000011',
    'b2000000-0000-4000-8000-000000000001',
    1,
    'vocabulary',
    'Choose the natural collocation.',
    'Este fin de semana quiero ___ una excursión a la montaña.',
    '["hacer", "poner", "dar"]'::jsonb,
    'hacer',
    'In Spanish, “hacer una excursión” is the natural expression for taking a trip or excursion.',
    null
  ),
  (
    'b2000000-0000-4000-8000-000000000012',
    'b2000000-0000-4000-8000-000000000001',
    2,
    'listening',
    'Listen, then answer the question.',
    '¿De qué depende el plan?',
    '["Del tiempo", "Del trabajo", "Del dinero"]'::jsonb,
    'Del tiempo',
    'The speaker says “si no llueve,” so the plan depends on the weather.',
    'Si no llueve, iremos a la playa el sábado por la mañana.'
  ),
  (
    'b2000000-0000-4000-8000-000000000013',
    'b2000000-0000-4000-8000-000000000001',
    3,
    'grammar',
    'Complete the future time clause.',
    'Cuando termine de trabajar, ___ a tomar algo con unos amigos.',
    '["salgo", "saldré", "saldría"]'::jsonb,
    'saldré',
    'After “cuando” refers to an unfinished future event, Spanish uses the present subjunctive “termine,” followed here by the future “saldré.”',
    null
  ),
  (
    'b2000000-0000-4000-8000-000000000014',
    'b2000000-0000-4000-8000-000000000001',
    4,
    'response',
    'Choose the most natural response.',
    'A friend asks: “¿Qué planes tienes para mañana?”',
    '["Todavía no lo tengo claro, pero quizá vaya al centro.", "Mañana fui al centro porque puedo.", "Tengo un plan que ayer será bueno."]'::jsonb,
    'Todavía no lo tengo claro, pero quizá vaya al centro.',
    '“Todavía no lo tengo claro” sounds natural, and “quizá vaya” correctly uses the subjunctive to express uncertainty.',
    null
  );
