create table public.vocabulary_themes (
  id text primary key,
  title text not null,
  description text not null,
  emoji text not null,
  sort_order integer not null default 0,
  is_published boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.vocabulary_sections (
  id uuid primary key default gen_random_uuid(),
  theme_id text not null references public.vocabulary_themes (id) on delete cascade,
  slug text not null,
  title text not null,
  description text not null,
  sort_order integer not null,
  constraint vocabulary_sections_theme_slug_unique unique (theme_id, slug)
);

create table public.vocabulary_items (
  id uuid primary key default gen_random_uuid(),
  section_id uuid not null references public.vocabulary_sections (id) on delete cascade,
  spanish text not null,
  english text not null,
  example_es text not null,
  example_en text not null,
  usage_note text,
  sort_order integer not null
);

create table public.user_vocabulary_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  item_id uuid not null references public.vocabulary_items (id) on delete cascade,
  status text not null default 'learning',
  confidence smallint not null default 1,
  correct_count integer not null default 0,
  incorrect_count integer not null default 0,
  last_seen_at timestamptz not null default now(),
  next_review_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_vocabulary_progress_status check (status in ('new', 'learning', 'confident')),
  constraint user_vocabulary_progress_confidence check (confidence between 0 and 3),
  constraint user_vocabulary_progress_counts check (correct_count >= 0 and incorrect_count >= 0),
  constraint user_vocabulary_progress_user_item_unique unique (user_id, item_id)
);

create index user_vocabulary_progress_review_idx
  on public.user_vocabulary_progress (user_id, next_review_at);

alter table public.vocabulary_themes enable row level security;
alter table public.vocabulary_sections enable row level security;
alter table public.vocabulary_items enable row level security;
alter table public.user_vocabulary_progress enable row level security;

create policy "Authenticated users can read published vocabulary themes"
  on public.vocabulary_themes for select to authenticated
  using (is_published);

create policy "Authenticated users can read published vocabulary sections"
  on public.vocabulary_sections for select to authenticated
  using (exists (
    select 1 from public.vocabulary_themes
    where vocabulary_themes.id = vocabulary_sections.theme_id
      and vocabulary_themes.is_published
  ));

create policy "Authenticated users can read published vocabulary items"
  on public.vocabulary_items for select to authenticated
  using (exists (
    select 1
    from public.vocabulary_sections
    join public.vocabulary_themes on vocabulary_themes.id = vocabulary_sections.theme_id
    where vocabulary_sections.id = vocabulary_items.section_id
      and vocabulary_themes.is_published
  ));

create policy "Users can read their own vocabulary progress"
  on public.user_vocabulary_progress for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can create their own vocabulary progress"
  on public.user_vocabulary_progress for insert to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their own vocabulary progress"
  on public.user_vocabulary_progress for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create function public.set_vocabulary_progress_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger user_vocabulary_progress_set_updated_at
  before update on public.user_vocabulary_progress
  for each row execute function public.set_vocabulary_progress_updated_at();

insert into public.vocabulary_themes (id, title, description, emoji, sort_order, is_published)
values ('dining-out', 'Dining Out', 'Order naturally, understand the menu, and handle the whole meal with confidence.', '🍽️', 1, true);

insert into public.vocabulary_sections (id, theme_id, slug, title, description, sort_order)
values
  ('d1000000-0000-4000-8000-000000000001', 'dining-out', 'getting-a-table', 'Getting a table', 'Arrive, ask about availability, and settle in.', 1),
  ('d1000000-0000-4000-8000-000000000002', 'dining-out', 'understanding-the-menu', 'Understanding the menu', 'Ask useful questions and understand what is offered.', 2),
  ('d1000000-0000-4000-8000-000000000003', 'dining-out', 'ordering-naturally', 'Ordering naturally', 'Sound comfortable rather than translating word by word.', 3),
  ('d1000000-0000-4000-8000-000000000004', 'dining-out', 'preferences', 'Preferences and needs', 'Explain dietary needs and customize an order politely.', 4),
  ('d1000000-0000-4000-8000-000000000005', 'dining-out', 'solving-problems', 'Solving a problem', 'Handle mistakes and delays calmly.', 5),
  ('d1000000-0000-4000-8000-000000000006', 'dining-out', 'paying', 'Paying and leaving', 'Ask for the bill, understand charges, and close the meal.', 6);

insert into public.vocabulary_items (section_id, spanish, english, example_es, example_en, usage_note, sort_order)
values
  ('d1000000-0000-4000-8000-000000000001', '¿Tienen mesa para dos?', 'Do you have a table for two?', 'Buenas noches, ¿tienen mesa para dos sin reserva?', 'Good evening, do you have a table for two without a reservation?', 'A natural first question when you arrive.', 1),
  ('d1000000-0000-4000-8000-000000000001', 'Tenemos una reserva a nombre de…', 'We have a reservation under the name…', 'Tenemos una reserva a nombre de Fulepp para las ocho.', 'We have a reservation under Fulepp for eight o’clock.', 'Use “a nombre de,” not a direct translation of “under.”', 2),
  ('d1000000-0000-4000-8000-000000000001', '¿Cuánto tiempo hay que esperar?', 'How long is the wait?', '¿Cuánto tiempo hay que esperar para una mesa en la terraza?', 'How long is the wait for a table on the terrace?', '“Hay que” is an impersonal way to express what is necessary.', 3),
  ('d1000000-0000-4000-8000-000000000001', 'Preferiríamos sentarnos afuera.', 'We would prefer to sit outside.', 'Si es posible, preferiríamos sentarnos afuera.', 'If possible, we would prefer to sit outside.', 'The conditional makes the preference polite.', 4),
  ('d1000000-0000-4000-8000-000000000001', '¿Nos pueden traer otra silla?', 'Could you bring us another chair?', 'Viene una persona más. ¿Nos pueden traer otra silla?', 'One more person is coming. Could you bring us another chair?', '“Nos pueden traer” is useful for many table requests.', 5),

  ('d1000000-0000-4000-8000-000000000002', '¿Qué me recomienda?', 'What do you recommend?', 'Es mi primera vez aquí. ¿Qué me recomienda?', 'It’s my first time here. What do you recommend?', 'Use singular “me recomienda” when addressing one server formally.', 1),
  ('d1000000-0000-4000-8000-000000000002', '¿Cuál es el plato del día?', 'What is today’s special?', '¿Cuál es el plato del día y con qué viene?', 'What is today’s special and what does it come with?', '“Plato del día” is widely understood.', 2),
  ('d1000000-0000-4000-8000-000000000002', '¿Qué lleva este plato?', 'What is in this dish?', '¿Qué lleva este plato? No reconozco uno de los ingredientes.', 'What is in this dish? I don’t recognize one of the ingredients.', '“Llevar” commonly means “to contain” when discussing food.', 3),
  ('d1000000-0000-4000-8000-000000000002', '¿Con qué viene?', 'What does it come with?', '¿Con qué viene el pescado?', 'What does the fish come with?', 'A concise way to ask about sides or accompaniments.', 4),
  ('d1000000-0000-4000-8000-000000000002', '¿Está muy picante?', 'Is it very spicy?', 'Me gusta el picante, pero ¿está muy picante?', 'I like spicy food, but is it very spicy?', '“Picante” means spicy-hot, not generally seasoned.', 5),

  ('d1000000-0000-4000-8000-000000000003', 'Quisiera pedir…', 'I would like to order…', 'Quisiera pedir el pulpo a la parrilla.', 'I would like to order the grilled octopus.', 'Polite and broadly useful across regions.', 1),
  ('d1000000-0000-4000-8000-000000000003', 'Para mí, …', 'For me, …', 'Para mí, la sopa de entrada y luego el pollo.', 'For me, the soup as a starter and then the chicken.', 'A very natural way to begin your order.', 2),
  ('d1000000-0000-4000-8000-000000000003', '¿Podemos pedir para compartir?', 'Can we order it to share?', '¿Podemos pedir varias entradas para compartir?', 'Can we order several starters to share?', 'Useful when ordering family-style.', 3),
  ('d1000000-0000-4000-8000-000000000003', '¿Nos da unos minutos más?', 'Could you give us a few more minutes?', 'Todavía no hemos decidido. ¿Nos da unos minutos más?', 'We haven’t decided yet. Could you give us a few more minutes?', '“Nos da” is natural and polite in this context.', 4),
  ('d1000000-0000-4000-8000-000000000003', 'Eso es todo por ahora.', 'That is all for now.', 'Dos copas de vino y una entrada. Eso es todo por ahora.', 'Two glasses of wine and a starter. That is all for now.', 'Leaves open the possibility of ordering more later.', 5),

  ('d1000000-0000-4000-8000-000000000004', '¿Esto lleva lácteos?', 'Does this contain dairy?', 'Soy intolerante a la lactosa. ¿Esto lleva lácteos?', 'I’m lactose intolerant. Does this contain dairy?', 'Replace “lácteos” with gluten, nueces, or mariscos as needed.', 1),
  ('d1000000-0000-4000-8000-000000000004', 'Soy alérgico / alérgica a…', 'I am allergic to…', 'Soy alérgica a los frutos secos.', 'I am allergic to nuts.', 'Match “alérgico” or “alérgica” to the speaker.', 2),
  ('d1000000-0000-4000-8000-000000000004', '¿Se puede preparar sin…?', 'Can it be prepared without…?', '¿Se puede preparar sin mantequilla?', 'Can it be prepared without butter?', 'Impersonal “se puede” keeps the request neutral.', 3),
  ('d1000000-0000-4000-8000-000000000004', 'Quisiera cambiar la guarnición.', 'I would like to change the side dish.', 'Quisiera cambiar la guarnición por una ensalada.', 'I would like to swap the side dish for a salad.', '“Guarnición” is the side served with a main dish.', 4),
  ('d1000000-0000-4000-8000-000000000004', '¿Me lo puede poner aparte?', 'Could you put it on the side?', '¿Me puede poner la salsa aparte?', 'Could you put the sauce on the side?', 'With a named item, say it directly; “lo” replaces a masculine item.', 5),

  ('d1000000-0000-4000-8000-000000000005', 'Disculpe, nos falta…', 'Excuse me, we are missing…', 'Disculpe, nos falta una de las bebidas.', 'Excuse me, we are missing one of the drinks.', '“Nos falta” focuses on what has not arrived.', 1),
  ('d1000000-0000-4000-8000-000000000005', 'Creo que esto no es lo que pedí.', 'I don’t think this is what I ordered.', 'Disculpe, creo que esto no es lo que pedí.', 'Excuse me, I don’t think this is what I ordered.', 'A tactful way to flag a mistake.', 2),
  ('d1000000-0000-4000-8000-000000000005', '¿Podrían calentarlo un poco más?', 'Could you warm it a little more?', 'Está un poco frío. ¿Podrían calentarlo un poco más?', 'It’s a little cold. Could you warm it a little more?', 'Conditional “podrían” softens the request.', 3),
  ('d1000000-0000-4000-8000-000000000005', 'Llevamos bastante tiempo esperando.', 'We have been waiting quite a while.', 'Perdone, llevamos bastante tiempo esperando el plato principal.', 'Excuse me, we have been waiting quite a while for the main course.', '“Llevar + time + gerund” expresses an ongoing duration.', 4),
  ('d1000000-0000-4000-8000-000000000005', '¿Podemos hablar con el encargado?', 'Can we speak with the manager?', '¿Podemos hablar con el encargado, por favor?', 'Can we speak with the manager, please?', 'Use when a problem cannot be resolved with the server.', 5),

  ('d1000000-0000-4000-8000-000000000006', '¿Nos trae la cuenta, por favor?', 'Could you bring us the bill, please?', 'Cuando pueda, ¿nos trae la cuenta, por favor?', 'When you can, could you bring us the bill, please?', '“La cuenta” is the restaurant bill.', 1),
  ('d1000000-0000-4000-8000-000000000006', '¿Podemos pagar por separado?', 'Can we pay separately?', 'Somos cuatro. ¿Podemos pagar por separado?', 'There are four of us. Can we pay separately?', 'Useful before the server processes payment.', 2),
  ('d1000000-0000-4000-8000-000000000006', '¿El servicio está incluido?', 'Is service included?', '¿El servicio está incluido en la cuenta?', 'Is service included in the bill?', 'Ask this before deciding whether to add a tip.', 3),
  ('d1000000-0000-4000-8000-000000000006', 'Quédese con el cambio.', 'Keep the change.', 'Está bien así. Quédese con el cambio.', 'That’s fine. Keep the change.', 'Formal command addressed to the server.', 4),
  ('d1000000-0000-4000-8000-000000000006', 'Todo estuvo muy rico.', 'Everything was delicious.', 'Muchas gracias. Todo estuvo muy rico.', 'Thank you very much. Everything was delicious.', 'In much of Latin America, “rico” is a natural compliment for food.', 5);
